parameters:
  name: null
  buildDependencies: []
  pool: {}
  matrix: {}
jobs:
- job: ${{ parameters.name }}
  condition: "
    and(
      not(contains(variables['manifest'], 'samples')),
      ${{ parameters.matrix }},
      or(
        and(
          succeeded(),
          eq(variables['singlePhase'], '')),
        eq(variables['singlePhase'], 'test')))"
  dependsOn:
  - GenerateMatrices
  - ${{ parameters.buildDependencies }}
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  steps:
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: published-images-$(osVersion)-$(architecture)
        targetPath: $(System.DefaultWorkingDirectory)/published-images
    - script:  >
        $(runImageBuilderCmd) import 
        --manifest $(manifest)
        $(imageBuilderPaths)
        --os-type $(osType)
        --os-version "$(osVersion)"
        --architecture $(architecture)
        --import-path $(System.DefaultWorkingDirectory)/published-images
      displayName: Import Images
  - template: ../steps/test-images-windows-client.yml
